# Generated by Django 4.0.1 on 2022-02-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daktarzusers',
            fields=[
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('symptom_names', models.CharField(max_length=255)),
                ('diagnosis_name', models.CharField(max_length=255)),
            ],
        ),
    ]
