# Generated by Django 4.0.1 on 2022-02-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daktarzusers',
            new_name='Daktarzuser',
        ),
    ]
