# Generated by Django 4.0.1 on 2022-03-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_rename_daktarzusers_daktarzuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='daktarzuser',
            name='user_age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='daktarzuser',
            name='user_gender',
            field=models.CharField(default='male', max_length=255),
        ),
    ]
